export default [
  { name: "Skye", tags: "Scotland UK Britain United Kingdom" },
  { name: "Britain", tags: "UK United Kingdom Endland Scotland Wales" },
  { name: "Ireland", tags: "Republic of Ireland Northern Ireland UK" },
  { name: "Iceland", tags: "" },
  { name: "Taiwan", tags: "" },
  { name: "Madagascar", tags: "" },
  { name: "Sri Lanka", tags: "" },
  { name: "Asia", tags: "Eurasia Europe" },
  { name: "New Guinea", tags: "Papua New Guinea Indonesia" },
  { name: "Sakhalin", tags: "Russia" },
  { name: "Sicily", tags: "Italy" },
  { name: "Hispaniola", tags: "Haiti Dominican Republic" },
  { name: "Luzon", tags: "The Philippines" },
  { name: "Jamaica", tags: "" },
  { name: "Mindanao", tags: "The Philippines" },
  { name: "Crete", tags: "Greece" },
  { name: "Mallorca", tags: "Spain Balleares" },
  { name: "Kyushu", tags: "Japan" },
  { name: "Shikoku", tags: "Japan" },
  { name: "Honshu", tags: "Japan" },
  { name: "Hokkaido", tags: "Japan" },
  { name: "Newfoundland", tags: "Canada" },
  { name: "Americas", tags: "The Americas North America South America" },
  { name: "Australia", tags: "" },
  { name: "Sardinia", tags: "Italy" },
  { name: "Te Ika-a-Maui ", tags: "New Zealand North Island" },
  { name: "Asia", tags: "Eurasia Europe" },
  { name: "Cyprus", tags: "" },
  { name: "Africa", tags: "" },
  { name: "Hawai'i", tags: "USA United States of America" },
  { name: "Svalbard", tags: "Norway" },
  { name: "Tierra del Fuego", tags: "Argentina Chile" },
  { name: "Greenland", tags: "Denmark" },
  { name: "Cuba", tags: "" },
  { name: "Baffin Island", tags: "Canada" },
  { name: "Puerto Rico", tags: "USA United States of America" },
  { name: "Sumatra", tags: "Indonesia" },
  { name: "Java", tags: "Indonesia" },
  { name: "Borneo", tags: "Malaysia Brunei Indonesia" },
  { name: "Te Waipounamu", tags: "New Zealand South Island" },
  { name: "Sulawesi", tags: "Indonesia" },
  { name: "Tasmania", tags: "Australia" },
  { name: "Corsica", tags: "France" },
  { name: "Hainan", tags: "China" },
  { name: "Aruba", tags: "ABW" },
  { name: "Afghanistan", tags: "AFG" },
  { name: "Angola", tags: "AGO" },
  { name: "Anguilla", tags: "AIA" },
  { name: "\u00c5land", tags: "ALA" },
  { name: "Albania", tags: "ALB" },
  { name: "Andorra", tags: "AND" },
  { name: "United Arab Emirates", tags: "ARE" },
  { name: "Argentina", tags: "ARG" },
  { name: "Armenia", tags: "ARM" },
  { name: "American Samoa", tags: "ASM" },
  { name: "French Southern Territories", tags: "ATF" },
  { name: "Antigua and Barbuda", tags: "ATG" },
  { name: "Australia", tags: "AUS" },
  { name: "Austria", tags: "AUT" },
  { name: "Azerbaijan", tags: "AZE" },
  { name: "Burundi", tags: "BDI" },
  { name: "Belgium", tags: "BEL" },
  { name: "Benin", tags: "BEN" },
  { name: "Bonaire, Sint Eustatius and Saba", tags: "BES" },
  { name: "Burkina Faso", tags: "BFA" },
  { name: "Bangladesh", tags: "BGD" },
  { name: "Bulgaria", tags: "BGR" },
  { name: "Bahrain", tags: "BHR" },
  { name: "Bahamas", tags: "BHS" },
  { name: "Bosnia and Herzegovina", tags: "BIH" },
  { name: "Saint-Barth\u00e9lemy", tags: "BLM" },
  { name: "Belarus", tags: "BLR" },
  { name: "Belize", tags: "BLZ" },
  { name: "Bermuda", tags: "BMU" },
  { name: "Bolivia", tags: "BOL" },
  { name: "Brazil", tags: "BRA" },
  { name: "Barbados", tags: "BRB" },
  { name: "Brunei", tags: "BRN" },
  { name: "Bhutan", tags: "BTN" },
  { name: "Bouvet Island", tags: "BVT" },
  { name: "Botswana", tags: "BWA" },
  { name: "Central African Republic", tags: "CAF" },
  { name: "Canada", tags: "CAN" },
  { name: "Cocos Islands", tags: "CCK" },
  { name: "Switzerland", tags: "CHE" },
  { name: "Chile", tags: "CHL" },
  { name: "China", tags: "CHN" },
  { name: "C\u00f4te d'Ivoire", tags: "CIV" },
  { name: "Cameroon", tags: "CMR" },
  { name: "Democratic Republic of the Congo", tags: "COD" },
  { name: "Republic of Congo", tags: "COG" },
  { name: "Cook Islands", tags: "COK" },
  { name: "Colombia", tags: "COL" },
  { name: "Comoros", tags: "COM" },
  { name: "Cape Verde", tags: "CPV" },
  { name: "Costa Rica", tags: "CRI" },
  { name: "Cuba", tags: "CUB" },
  { name: "Cura\u00e7ao", tags: "CUW" },
  { name: "Christmas Island", tags: "CXR" },
  { name: "Cayman Islands", tags: "CYM" },
  { name: "Cyprus", tags: "CYP" },
  { name: "Czech Republic", tags: "CZE" },
  { name: "Germany", tags: "DEU" },
  { name: "Djibouti", tags: "DJI" },
  { name: "Dominica", tags: "DMA" },
  { name: "Denmark", tags: "DNK" },
  { name: "Dominican Republic", tags: "DOM" },
  { name: "Algeria", tags: "DZA" },
  { name: "Ecuador", tags: "ECU" },
  { name: "Egypt", tags: "EGY" },
  { name: "Eritrea", tags: "ERI" },
  { name: "Western Sahara", tags: "ESH" },
  { name: "Spain", tags: "ESP" },
  { name: "Estonia", tags: "EST" },
  { name: "Ethiopia", tags: "ETH" },
  { name: "Finland", tags: "FIN" },
  { name: "Fiji", tags: "FJI" },
  { name: "Falkland Islands", tags: "FLK" },
  { name: "France", tags: "FRA" },
  { name: "Faroe Islands", tags: "FRO" },
  { name: "Micronesia", tags: "FSM" },
  { name: "Gabon", tags: "GAB" },
  { name: "United Kingdom", tags: "GBR" },
  { name: "Georgia", tags: "GEO" },
  { name: "Guernsey", tags: "GGY" },
  { name: "Ghana", tags: "GHA" },
  { name: "Gibraltar", tags: "GIB" },
  { name: "Guinea", tags: "GIN" },
  { name: "Guadeloupe", tags: "GLP" },
  { name: "Gambia", tags: "GMB" },
  { name: "Guinea-Bissau", tags: "GNB" },
  { name: "Equatorial Guinea", tags: "GNQ" },
  { name: "Greece", tags: "GRC" },
  { name: "Grenada", tags: "GRD" },
  { name: "Greenland", tags: "GRL" },
  { name: "Guatemala", tags: "GTM" },
  { name: "French Guiana", tags: "GUF" },
  { name: "Guam", tags: "GUM" },
  { name: "Guyana", tags: "GUY" },
  { name: "Hong Kong", tags: "HKG" },
  { name: "Heard Island and McDonald Islands", tags: "HMD" },
  { name: "Honduras", tags: "HND" },
  { name: "Croatia", tags: "HRV" },
  { name: "Haiti", tags: "HTI" },
  { name: "Hungary", tags: "HUN" },
  { name: "Indonesia", tags: "IDN" },
  { name: "Isle of Man", tags: "IMN" },
  { name: "India", tags: "IND" },
  { name: "British Indian Ocean Territory", tags: "IOT" },
  { name: "Ireland", tags: "IRL" },
  { name: "Iran", tags: "IRN" },
  { name: "Iraq", tags: "IRQ" },
  { name: "Iceland", tags: "ISL" },
  { name: "Israel", tags: "ISR" },
  { name: "Italy", tags: "ITA" },
  { name: "Jamaica", tags: "JAM" },
  { name: "Jersey", tags: "JEY" },
  { name: "Jordan", tags: "JOR" },
  { name: "Japan", tags: "JPN" },
  { name: "Kazakhstan", tags: "KAZ" },
  { name: "Kenya", tags: "KEN" },
  { name: "Kyrgyzstan", tags: "KGZ" },
  { name: "Cambodia", tags: "KHM" },
  { name: "Kiribati", tags: "KIR" },
  { name: "Saint Kitts and Nevis", tags: "KNA" },
  { name: "South Korea", tags: "KOR" },
  { name: "Kuwait", tags: "KWT" },
  { name: "Laos", tags: "LAO" },
  { name: "Lebanon", tags: "LBN" },
  { name: "Liberia", tags: "LBR" },
  { name: "Libya", tags: "LBY" },
  { name: "Saint Lucia", tags: "LCA" },
  { name: "Liechtenstein", tags: "LIE" },
  { name: "Sri Lanka", tags: "LKA" },
  { name: "Lesotho", tags: "LSO" },
  { name: "Lithuania", tags: "LTU" },
  { name: "Luxembourg", tags: "LUX" },
  { name: "Latvia", tags: "LVA" },
  { name: "Macao", tags: "MAC" },
  { name: "Saint-Martin", tags: "MAF" },
  { name: "Morocco", tags: "MAR" },
  { name: "Monaco", tags: "MCO" },
  { name: "Moldova", tags: "MDA" },
  { name: "Madagascar", tags: "MDG" },
  { name: "Maldives", tags: "MDV" },
  { name: "Mexico", tags: "MEX" },
  { name: "Marshall Islands", tags: "MHL" },
  { name: "Macedonia", tags: "MKD" },
  { name: "Mali", tags: "MLI" },
  { name: "Malta", tags: "MLT" },
  { name: "Myanmar", tags: "MMR" },
  { name: "Montenegro", tags: "MNE" },
  { name: "Mongolia", tags: "MNG" },
  { name: "Northern Mariana Islands", tags: "MNP" },
  { name: "Mozambique", tags: "MOZ" },
  { name: "Mauritania", tags: "MRT" },
  { name: "Montserrat", tags: "MSR" },
  { name: "Martinique", tags: "MTQ" },
  { name: "Mauritius", tags: "MUS" },
  { name: "Malawi", tags: "MWI" },
  { name: "Malaysia", tags: "MYS" },
  { name: "Mayotte", tags: "MYT" },
  { name: "Namibia", tags: "NAM" },
  { name: "New Caledonia", tags: "NCL" },
  { name: "Niger", tags: "NER" },
  { name: "Norfolk Island", tags: "NFK" },
  { name: "Nigeria", tags: "NGA" },
  { name: "Nicaragua", tags: "NIC" },
  { name: "Niue", tags: "NIU" },
  { name: "Netherlands", tags: "NLD" },
  { name: "Norway", tags: "NOR" },
  { name: "Nepal", tags: "NPL" },
  { name: "Nauru", tags: "NRU" },
  { name: "New Zealand", tags: "NZL" },
  { name: "Oman", tags: "OMN" },
  { name: "Pakistan", tags: "PAK" },
  { name: "Panama", tags: "PAN" },
  { name: "Pitcairn Islands", tags: "PCN" },
  { name: "Peru", tags: "PER" },
  { name: "Philippines", tags: "PHL" },
  { name: "Palau", tags: "PLW" },
  { name: "Papua New Guinea", tags: "PNG" },
  { name: "Poland", tags: "POL" },
  { name: "Puerto Rico", tags: "PRI" },
  { name: "North Korea", tags: "PRK" },
  { name: "Portugal", tags: "PRT" },
  { name: "Paraguay", tags: "PRY" },
  { name: "Palestina", tags: "PSE" },
  { name: "French Polynesia", tags: "PYF" },
  { name: "Qatar", tags: "QAT" },
  { name: "Reunion", tags: "REU" },
  { name: "Romania", tags: "ROU" },
  { name: "Russia", tags: "RUS" },
  { name: "Rwanda", tags: "RWA" },
  { name: "Saudi Arabia", tags: "SAU" },
  { name: "Sudan", tags: "SDN" },
  { name: "Senegal", tags: "SEN" },
  { name: "Singapore", tags: "SGP" },
  { name: "South Georgia and the South Sandwich Islands", tags: "SGS" },
  { name: "Saint Helena", tags: "SHN" },
  { name: "Svalbard and Jan Mayen", tags: "SJM" },
  { name: "Solomon Islands", tags: "SLB" },
  { name: "Sierra Leone", tags: "SLE" },
  { name: "El Salvador", tags: "SLV" },
  { name: "San Marino", tags: "SMR" },
  { name: "Somalia", tags: "SOM" },
  { name: "Saint Pierre and Miquelon", tags: "SPM" },
  { name: "Serbia", tags: "SRB" },
  { name: "South Sudan", tags: "SSD" },
  { name: "S\u00e3o Tom\u00e9 and Pr\u00edncipe", tags: "STP" },
  { name: "Suriname", tags: "SUR" },
  { name: "Slovakia", tags: "SVK" },
  { name: "Slovenia", tags: "SVN" },
  { name: "Sweden", tags: "SWE" },
  { name: "Swaziland", tags: "SWZ" },
  { name: "Sint Maarten", tags: "SXM" },
  { name: "Seychelles", tags: "SYC" },
  { name: "Syria", tags: "SYR" },
  { name: "Turks and Caicos Islands", tags: "TCA" },
  { name: "Chad", tags: "TCD" },
  { name: "Togo", tags: "TGO" },
  { name: "Thailand", tags: "THA" },
  { name: "Tajikistan", tags: "TJK" },
  { name: "Tokelau", tags: "TKL" },
  { name: "Turkmenistan", tags: "TKM" },
  { name: "Timor-Leste", tags: "TLS" },
  { name: "Tonga", tags: "TON" },
  { name: "Trinidad and Tobago", tags: "TTO" },
  { name: "Tunisia", tags: "TUN" },
  { name: "Turkey", tags: "TUR" },
  { name: "Tuvalu", tags: "TUV" },
  { name: "Taiwan", tags: "TWN" },
  { name: "Tanzania", tags: "TZA" },
  { name: "Uganda", tags: "UGA" },
  { name: "Ukraine", tags: "UKR" },
  { name: "United States Minor Outlying Islands", tags: "UMI" },
  { name: "Uruguay", tags: "URY" },
  { name: "United States", tags: "USA" },
  { name: "Uzbekistan", tags: "UZB" },
  { name: "Vatican City", tags: "VAT" },
  { name: "Saint Vincent and the Grenadines", tags: "VCT" },
  { name: "Venezuela", tags: "VEN" },
  { name: "British Virgin Islands", tags: "VGB" },
  { name: "Virgin Islands, U.S.", tags: "VIR" },
  { name: "Vietnam", tags: "VNM" },
  { name: "Vanuatu", tags: "VUT" },
  { name: "Wallis and Futuna", tags: "WLF" },
  { name: "Samoa", tags: "WSM" },
  { name: "Akrotiri and Dhekelia", tags: "XAD" },
  { name: "Caspian Sea", tags: "XCA" },
  { name: "Clipperton Island", tags: "XCL" },
  { name: "Kosovo", tags: "XKO" },
  { name: "Northern Cyprus", tags: "XNC" },
  { name: "Paracel Islands", tags: "XPI" },
  { name: "Spratly Islands", tags: "XSP" },
  { name: "Yemen", tags: "YEM" },
  { name: "South Africa", tags: "ZAF" },
  { name: "Zambia", tags: "ZMB" },
  { name: "Zimbabwe", tags: "ZWE" },
];
